---
- name: Installing and Launching Metricbeat
  hosts: webservers
  become: yes
  tasks:

  - name: Download metricbeat .deb file
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

  - name: Insall metricbeat .deb
    command: dpkg -i metricbeat-7.6.1-amd64.deb

  - name: Drop in metricbeat.yml
    copy:
     src: /etc/ansible/metricbeat-config.yml
     dest: /etc/metricbeat/metricbeat.yml

  - name: Enable and Configure Docker Module for Metric Beat
    command: metricbeat modules enable docker

  - name: Setup Metric Beat
    command: metricbeat setup

  - name: Start Metric Beat
    command: service metricbeat start

  - name: Enable Service Metricbeat on Boot
    systemd:
     name: metricbeat
     enabled: yes
